import { SpanType, type Span, type Trace } from '../core/types.js';
import {
  generatedError,
  generatedMetadata,
  identifierFromName,
  jsonLiteral,
  pathSegmentFromName,
  serializedValue,
  spanMatchesFilter,
  uniqueIdentifier,
  type GenerationFilter
} from '../generation/shared.js';

/** Output format for generated fixture files. */
export type FixtureGenerationFormat = 'json' | 'typescript';

/** Filters selecting which recorded spans produce fixture files. */
export interface FixtureGenerationFilter {
  /** Span type to include. */
  readonly type?: SpanType | string;
  /** Span name to include, matched exactly for strings or via RegExp. */
  readonly name?: string | RegExp;
}

/** Options controlling fixture extraction from a trace. */
export interface GenerateFixturesOptions {
  /** Fixture output format. Defaults to JSON files. */
  readonly format?: FixtureGenerationFormat;
  /** Optional filter limiting which spans produce fixtures. */
  readonly filter?: FixtureGenerationFilter;
  /** Whether spans with recorded errors should be included. Defaults to true. */
  readonly includeErrors?: boolean;
}

interface FixtureGroup {
  readonly type: SpanType;
  readonly name: string;
  readonly pathBase: string;
  readonly exportName: string;
  readonly spans: readonly Span[];
}

interface FixtureEntry {
  readonly spanId: string;
  readonly input: unknown;
  readonly output: unknown;
  readonly error: unknown;
  readonly metadata: unknown;
  readonly duration: number;
}

interface FixturePayload {
  readonly traceId: string;
  readonly traceName: string;
  readonly traceMetadata: unknown;
  readonly spanType: SpanType;
  readonly spanName: string;
  readonly entries: readonly FixtureEntry[];
}

function normalizeFormat(format: FixtureGenerationFormat | undefined): FixtureGenerationFormat {
  if (format === undefined) {
    return 'json';
  }
  if (format === 'json' || format === 'typescript') {
    return format;
  }

  throw new Error(`Unsupported fixture generation format "${String(format)}". Expected json or typescript.`);
}

function groupSpans(trace: Trace, filter: GenerationFilter | undefined, includeErrors: boolean): readonly Omit<FixtureGroup, 'pathBase' | 'exportName'>[] {
  const grouped = new Map<string, { type: SpanType; name: string; spans: Span[] }>();

  for (const span of trace.spans) {
    if (span.error !== null && !includeErrors) {
      continue;
    }
    if (!spanMatchesFilter(span, filter)) {
      continue;
    }

    const key = `${span.type}\u0000${span.name}`;
    const existing = grouped.get(key);
    if (existing === undefined) {
      grouped.set(key, {
        type: span.type,
        name: span.name,
        spans: [span]
      });
    } else {
      existing.spans.push(span);
    }
  }

  return Array.from(grouped.values()).filter((group) => group.spans.length > 0);
}

function withGeneratedNames(groups: readonly Omit<FixtureGroup, 'pathBase' | 'exportName'>[]): readonly FixtureGroup[] {
  const usedPathKeys = new Set<string>();
  const usedExportNames = new Set<string>();

  return groups.map((group) => {
    const basePath = pathSegmentFromName(group.name);
    let pathBase = basePath;
    let suffix = 2;
    let pathKey = `${group.type}/${pathBase}`;

    while (usedPathKeys.has(pathKey)) {
      pathBase = `${basePath}-${suffix}`;
      pathKey = `${group.type}/${pathBase}`;
      suffix += 1;
    }

    usedPathKeys.add(pathKey);

    return {
      ...group,
      pathBase,
      exportName: uniqueIdentifier(identifierFromName(`${group.type}_${pathBase}`), usedExportNames)
    };
  });
}

function entryForSpan(span: Span): FixtureEntry {
  return {
    spanId: span.id,
    input: serializedValue(span.input),
    output: serializedValue(span.output),
    error: generatedError(span.error),
    metadata: serializedValue(span.metadata),
    duration: span.duration
  };
}

function payloadForGroup(trace: Trace, group: FixtureGroup): FixturePayload {
  return {
    traceId: trace.id,
    traceName: trace.name,
    traceMetadata: generatedMetadata(trace.metadata),
    spanType: group.type,
    spanName: group.name,
    entries: group.spans.map(entryForSpan)
  };
}

function header(): string {
  return [
    '/* Generated by GhostTrace fixture generation. */',
    '/* eslint-disable */'
  ].join('\n');
}

function jsonFixture(payload: FixturePayload): string {
  return `${jsonLiteral(payload)}\n`;
}

function typescriptFixture(payload: FixturePayload): string {
  return `${header()}\n\nexport const fixture = ${jsonLiteral(payload)} as const;\n`;
}

function fixturePath(group: FixtureGroup, format: FixtureGenerationFormat): string {
  return `${group.type}/${group.pathBase}.${format === 'json' ? 'json' : 'ts'}`;
}

function indexSource(groups: readonly FixtureGroup[], format: FixtureGenerationFormat): string {
  const exportLines = groups.map((group) => {
    if (format === 'json') {
      return `export { default as ${group.exportName} } from './${group.type}/${group.pathBase}.json';`;
    }

    return `export { fixture as ${group.exportName} } from './${group.type}/${group.pathBase}.js';`;
  });
  const pathEntries = groups.map((group) => `  ${group.exportName}: ${JSON.stringify(fixturePath(group, format))}`);

  return [
    header(),
    ...exportLines,
    '',
    'export const fixturePaths = {',
    pathEntries.join(',\n'),
    '} as const;'
  ].join('\n').concat('\n');
}

/** Extracts recorded span input/output values as fixture files organized by span type and name. */
export function generateFixtures(trace: Trace, options: GenerateFixturesOptions = {}): Map<string, string> {
  const format = normalizeFormat(options.format);
  const groups = withGeneratedNames(groupSpans(trace, options.filter, options.includeErrors ?? true));
  const files = new Map<string, string>();

  for (const group of groups) {
    const payload = payloadForGroup(trace, group);
    files.set(
      fixturePath(group, format),
      format === 'json' ? jsonFixture(payload) : typescriptFixture(payload)
    );
  }

  files.set('index.ts', indexSource(groups, format));
  return files;
}
